parameters:

    freepayment.controller.route.name: "freepayment_execute"
    freepayment.manager.class: "PaymentSuite\\FreePaymentBundle\\Services\\PaymillManager"
    freepayment.routes.loader.class: "PaymentSuite\\FreePaymentBundle\\Router\\PaymillRoutesLoader"